export const E_COLOR_THEME_NOT_FOUND: string = 'E_COLOR_THEME_NOT_FOUND'
export const E_COMMAND_NOT_FOUND: string = 'E_COMMAND_NOT_FOUND'
export const E_ICON_THEME_NOT_FOUND: string = 'E_ICON_THEME_NOT_FOUND'
export const E_INCOMPATIBLE_NATIVE_MODULE: string =
  'E_INCOMPATIBLE_NATIVE_MODULE'
export const E_MANIFEST_NOT_FOUND: string = 'E_MANIFEST_NOT_FOUND'
export const E_MODULES_NOT_SUPPORTED_IN_ELECTRON: string =
  'E_MODULES_NOT_SUPPORTED_IN_ELECTRON'
export const E_JSON_PARSE: string = 'E_JSON_PARSE'
export const EACCES: string = 'EACCES'
export const ECONNRESET: string = 'ECONNRESET'
export const EEXIST: string = 'EEXIST'
export const EISDIR: string = 'EISDIR'
export const ELOOP: string = 'ELOOP'
export const ENOENT: string = 'ENOENT'
export const ENOTDIR: string = 'ENOTDIR'
export const EPERM: string = 'EPERM'
export const EPIPE: string = 'EPIPE'
export const ERR_IPC_CHANNEL_CLOSED: string = 'ERR_IPC_CHANNEL_CLOSED'
export const ERR_MODULE_NOT_FOUND: string = 'ERR_MODULE_NOT_FOUND'
export const EXDEV: string = 'EXDEV'
export const ERR_DLOPEN_FAILED: string = 'ERR_DLOPEN_FAILED'
export const ESRCH: string = 'ESRCH'
export const E_RIP_GREP_NOT_FOUND: string = 'E_RIP_GREP_NOT_FOUND'
